#version 430
layout(local_size_x = 8, local_size_y = 4) in;
layout(rgba32f, binding = 0) uniform writeonly image2D u_output;

vec4 per_pixel(ivec2 coord, ivec2 resolution) {
    return vec4(1.0, 0.5, 0.5, 1.0);
}

void main() {
    ivec2 pixel_coord = ivec2(gl_GlobalInvocationID.xy);
    ivec2 resolution = imageSize(u_output);

    vec4 color = per_pixel(pixel_coord, resolution);

    imageStore(u_output, pixel_coord, color);
}